default:
  target: dev
  outputs:
    dev:
      type: bigquery
      threads: 16
      database: airbnb-495108
      schema: airbnb_data
      method: service-account
      keyfile: "{{ env_var('GOOGLE_APPLICATION_CREDENTIALS') }}"
      location: US
      dataproc_batch: null